---
##################################################
# Name: debug
# Description: Prints env vars.
##################################################

stages:
  - debug

include:
  - remote: "https://git.saltlabs.cloud/templates/gitlab-ci/-/raw/main/Jobs/debug.gitlab-ci.yml"

environment-linux-amd64:
  extends:
    - ".environment"
  variables:
    PLATFORM: "linux/amd64"
  rules:
    - if: '$PLATFORM_AMD64 == "TRUE"'
      when: on_success

environment-linux-arm64:
  extends:
    - ".environment"
  variables:
    PLATFORM: "linux/arm64"
  rules:
    - if: '$PLATFORM_ARM64 == "TRUE"'
      when: on_success

environment-linux-arm:
  extends:
    - ".environment"
  variables:
    PLATFORM: "linux/arm"
  rules:
    - if: '$PLATFORM_ARM == "TRUE"'
      when: on_success
