---
#########################
# Name: KICS
# Description: Keep Infrastructure Code Secure
# Notes:
#########################

.kics-iac:
  needs: []
  dependencies: null
  image:
    name: artefacts.saltlabs.cloud/docker/checkmarx/kics:latest
  script:
    - kics scan
      --no-progress
      --ignore-on-exit all
      -p ${PWD}
      -o ${PWD}
      --report-formats "glsast"
      --output-name kics-result
    - kics scan
      --no-progress
      --ignore-on-exit all
      -p ${PWD}
      -o ${PWD}
      --report-formats "codeclimate"
      --output-name codeclimate-kics-result
    - kics scan
      --no-progress
      --ignore-on-exit all
      -p ${PWD}
      -o ${PWD}
      --report-formats "pdf"
      --output-name kics-result
  artifacts:
    paths:
      - kics-result.pdf
      - codeclimate-kics-result.json
      - gl-sast-kics-result.json
    reports:
      codequality: codeclimate-kics-result.json
      sast: gl-sast-kics-result.json
    when: always
  rules:
    # Lint on commits to match GitLab templates.
    - if: "$CI_COMMIT_BRANCH"
      changes:
        - "**/*.yml"
        - "**/*.yaml"
        - "**/*.gitlab-ci.yml"
      when: on_success
  allow_failure: true
