---
#########################
# Name: markdownlint
# Description: Executes markdownlint
# Documentation: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
# Notes:
#   * A simple job that executes markdownlint. By default in a non-blocking mode
#   which can be switched to blocking by the enablement of 'strict' mode.
#
#   * The job assumes default configuration file location within the local
#   repository which ca be overridden if required.
#
#   * Defaults to running during the MR process only.
#########################

.markdownlint:
  needs: []
  dependencies: null
  image:
    name: artefacts.saltlabs.cloud/docker/pipeline-components/markdownlint:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MARKDOWNLINT_CONFIG: ".gitlab/linters/.markdownlint.yml"
    MARKDOWNLINT_ENABLE_STRICT: "FALSE"
  script:
    - |
      [[ ! -f "${MARKDOWNLINT_CONFIG}" ]] && (echo "Missing linter config ${MARKDOWNLINT_CONFIG}" >&2; exit 1)
    - |
      if [[ "${MARKDOWNLINT_ENABLE_STRICT}" == "TRUE" ]];
      then
        echo "Linting Markdown in strict mode..."
        mdl \
          --config ${MARKDOWNLINT_CONFIG} \
          --verbose \
          --warnings
          .
      else
        echo "Linting Markdown..."
        mdl \
          --config ${MARKDOWNLINT_CONFIG} \
          --verbose \
          --warning \
          . \
          || true
      fi
  rules:
    # Lint on changes to MRs
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "**/*.md"
      when: on_success
  allow_failure: false
