---
#########################
# Name: mattermost
# Description: Sends a message to a Mattermost channel via a webhook.
# Reference: https://developers.mattermost.com/integrate/webhooks/outgoing/
#########################

.mattermost:
  needs: []
  dependencies: null
  image:
    name: artefacts.saltlabs.cloud/docker/debian:bullseye-slim
  variables:
    MATTERMOST_RESPONSE_TYPE: "post"
    MATTERMOST_USERNAME: "mattermost"
    MATTERMOST_ICON_URL: "https://mattermost.saltlabs.cloud/static/images/favicon/favicon-default-32x32.png"
    MATTERMOST_MESSAGE: "No message was provided."
  before_script:
    # Check the required variables exist.
    - |
      [[ -z "${MATTERMOST_WEBHOOK}" ]] && (echo "MATTERMOST_WEBHOOK must be set" >&2; exit 1)
    # Install dependencies
    - apt update
    - apt install --yes curl jq
  script:
    - echo "Sending Mattermost message as ${MATTERMOST_USERNAME} via the provided webhook."
    - |
      declare -a CURL_OPTIONS=(
        '--silent'
        '--insecure'
        '--header'
        "Content-Type: application/json"
      )
    - |
      echo "Building Mattermost data"
      CURL_DATA=$(cat <<EOF
      {
        "response_type" : "${MATTERMOST_RESPONSE_TYPE}",
        "username" : "${MATTERMOST_USERNAME}",
        "icon_url" : "${MATTERMOST_ICON_URL}",
        "text" : "${MATTERMOST_MESSAGE}"
      }
      EOF
      )
    # Debug info
    - |
      if [[ "${DEBUG:-FALSE}" == "TRUE" ]];
      then
        echo "DEBUG: The Mattermost data is:"
        echo "${CURL_DATA}" | jq
      fi
    - |
      if ! RESPONSE=$(curl "${CURL_OPTIONS[@]}" --request POST --data "${CURL_DATA}" "${MATTERMOST_WEBHOOK}");
      then
        echo "Mattermost message failed to be sent"
        exit 1
      else
        # If it works, then the response is "ok"
        if ! grep "ok" <<< ${RESPONSE} >/dev/null;
        then
          STATUS_CODE=$(echo $RESPONSE | jq .status_code || true)
          echo "Mattermost Webhook error!"
          echo "Status Code: ${STATUS_CODE}"
          echo "Full Response: ${RESPONSE}"
          exit 1
        else
          echo "Mattermost message sent successfully!"
          exit 0
        fi
      fi
  allow_failure: false
