---
##################################################
# Name: megalinter
# Description: GitLab CI configuration for MegaLinter
##################################################

.megalinter:
  needs: []
  dependencies: null
  image:
    name: artefacts.saltlabs.cloud/docker/oxsecurity/megalinter:v6
  variables:
    # Override this for strict mode.
    DISABLE_ERRORS: "true"
    DEFAULT_WORKSPACE: "$CI_PROJECT_DIR"
    MEGALINTER_CONFIG: ".gitlab/linters/.mega-linter.yml"
    GITLAB_ACCESS_TOKEN_MEGALINTER: "${GIT_BOT_TOKEN}"
  script:
    - "/bin/bash /entrypoint.sh"
  artifacts:
    when: always
    paths:
      - megalinter-reports
    expire_in: 1 week
  rules:
    # Lint on changes to MRs
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    # Don't run under other conditions.
    - when: never
  allow_failure: true
