---
##################################################
# Name: super-linter
# Description: GitLab CI configuration for GitHub's super-linter
# Reference: https://github.com/github/super-linter
##################################################

.super-linter:
  needs: []
  dependencies: null
  image:
    name: artefacts.saltlabs.cloud/docker/github/super-linter:latest
    entrypoint: [""]
  variables:
    # Override this for strict mode.
    DISABLE_ERRORS: "true"
    RUN_LOCAL: "true"
    LINTER_RULES_PATH: $CI_PROJECT_DIR/.gitlab/linters
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    ANSIBLE_DIRECTORY: $CI_PROJECT_DIR
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
    OUTPUT_FORMAT: "tap"
    OUTPUT_DETAILS: "detailed"
    OUTPUT_FOLDER: "reports"
    CONVERTED_OUTPUT_FOLDER: "reports-xml"
    TAP_JUNIT_VERSION: "4.0.0"
    REPORT_SUITE_TEST_NAME: "super_linter"
  script:
    - mkdir reports
    - /action/lib/linter.sh
  after_script:
    - npm install -g tap-junit@${TAP_JUNIT_VERSION}
    - mkdir ${CONVERTED_OUTPUT_FOLDER}
    - cd ${OUTPUT_FOLDER}
    - |
      for REPORT in *;
      do
        if [[ -f ${REPORT} ]];
        then
          echo "Processing report ${REPORT}"
          'sed -i "s/message: \*\+/message: /g" $REPORT'
          # convert each tap file to junit xml
          cat $REPORT | tap-junit -p -s "${REPORT_SUITE_TEST_NAME}" > ../${CONVERTED_OUTPUT_FOLDER}/${REPORT}.xml
          # extract message to improve REPORT display
          sed -i 's/<failure message="\(.\+\)" type="fail">.*/<failure message="" type="fail">\n\1\n<\/failure>/g' ../${CONVERTED_OUTPUT_FOLDER}/${REPORT}.xml
          # Add newlines
          sed -i 's/\\n/\n/g' ../${CONVERTED_OUTPUT_FOLDER}/${REPORT}.xml
          # remove double </failure> that break the syntax in some REPORTs
          sed -i ':begin;$!N;s/<\/failure>\n<\/failure>/<\/failure>/;tbegin;P;D' ../${CONVERTED_OUTPUT_FOLDER}/${REPORT}.xml
        fi
      done
    - echo "Finished processing reports"
  artifacts:
    paths:
      - "${OUTPUT_FOLDER}/*.tap"
    when: always
    reports:
      junit: "${CONVERTED_OUTPUT_FOLDER}/*.xml"
  rules:
    # Lint on changes to MRs
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    # Don't run under other conditions.
    - when: never
  allow_failure: false
