---
##################################################
# Name: vra_teardown
# Description: Removes a host in vRA.
# Notes:
#   * A CI variable GITLAB_VRA_TOKEN is required to be set with a token that
#     has permissions to access the vRA API.
##################################################

.vra-teardown:
  when: manual
  image:
    name: artefacts.saltlabs.cloud/docker/vra-rest-utility:latest
  script:
    - |
      # kics-scan ignore-line
      [[ "${GITLAB_VRA_TOKEN:-EMPTY}" == "EMPTY" ]] && (echo "GITLAB_VRA_TOKEN must be set" >&2; exit 1)
    - vraRESTUtil -t ${GITLAB_VRA_TOKEN} deployment --delete -dn "${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"

  artifacts:
    paths:
      - "output"
