---
#########################
# Name: yamllint
# Description: Executes yamllint
# Documentation: https://yamllint.readthedocs.io/
# Notes:
#   * A simple job that executes yamllint. By default in a non-blocking mode
#   which can be switched to blocking by the enablement of 'strict' mode.
#
#   * The job assumes default configuration file location within the local
#   repository which can be overridden if required.
#
#   * Defaults to running during the MR process only.
#########################

.yamllint:
  needs: []
  dependencies: null
  image:
    name: artefacts.saltlabs.cloud/docker/pipeline-components/yamllint:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    YAMLLINT_CONFIG: ".gitlab/linters/.yamllint.yml"
    YAMLLINT_ENABLE_STRICT: "FALSE"
  script:
    - yamllint --version
    - |
      [[ ! -f "${YAMLLINT_CONFIG}" ]] && (echo "Missing linter config ${YAMLLINT_CONFIG}" >&2; exit 1)
    - |
      if [[ "${YAMLLINT_ENABLE_STRICT}" == "TRUE" ]];
      then
        echo "Running YAMLLint with strict mode enabled..."
        yamllint --config-file "${YAMLLINT_CONFIG}" --strict .
      else
        echo "Running YAMLLint with strict mode disabled..."
        yamllint --config-file "${YAMLLINT_CONFIG}" .
      fi
  rules:
    # Lint on changes to MRs
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "**/*.yml"
        - "**/*.yaml"
        - "**/*.gitlab-ci.yml"
      when: on_success
  allow_failure: false
