---

##################################################
# Name: .markdownlint.yml
# Description: Markdown linter configuration
#
# NOTES:
#
##################################################

# No hard tabs allowed
no-hard-tabs: true

# Unordered list indentation
MD007:
  indent: 4

# Trailing spaces
MD009:
  br_spaces: 2

# Line length
MD013: false

# Inline HTML
MD033: false

# List marker spaces
# Disabled for use with prettier
MD030: false
