---

##################################################
# Name: .yamllint.yml
# Description: YAMLLint configuration
#
# Notes:
#       - You can disable line with 'yamllint disable-line'
#
# Reference: https://yamllint.readthedocs.io/en/latest/
##################################################

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.gitlab-ci.yml'

rules:

  braces:
    level: warning
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 5

  brackets:
    level: warning
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 5

  colons:
    level: warning
    max-spaces-before: 0
    max-spaces-after: 1

  commas:
    level: warning
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  comments: disable
  comments-indentation: disable

  document-start:
    level: warning
    present: true
  document-end: disable

  empty-lines:
    level: warning
    max: 2
    max-start: 0
    max-end: 0

  hyphens:
    level: warning
    max-spaces-after: 1

  indentation:
    level: warning
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false

  key-duplicates: enable

  line-length: disable

  new-line-at-end-of-file: disable

  new-lines:
    type: unix

  trailing-spaces: disable
