---
#########################
# Name: mattermost
# Description: An example workflow sending a message to Mattermost.
# Usage:
#   * Copy and paste the relevant sections below into .gitlab-ci.yml
#   * Customise your variables including the message.
#   * Include the changes through the MR process.
#########################

stages:
  - mattermost

include:
  - remote: "https://git.saltlabs.cloud/templates/gitlab-ci/-/raw/main/Jobs/mattermost.gitlab-ci.yml"

# Example sending a message when the CI job was successful.
mattermost-success:
  stage: mattermost
  extends:
    - ".mattermost"
  variables:
    MATTERMOST_WEBHOOK: "https://webhook_url_goes_here"
    MATTERMOST_USERNAME: "some-optional-username"
    MATTERMOST_ICON_URL: "https://optional-url-here/favicon.ico"
    MATTERMOST_MESSAGE: "My important message goes here on success! -> ${CI_JOB_URL}"
  rules:
    - on_success

# Example sending a message when the CI job failed.
mattermost-failure:
  stage: mattermost
  extends:
    - ".mattermost"
  variables:
    MATTERMOST_WEBHOOK: "https://webhook_url_goes_here"
    MATTERMOST_USERNAME: "some-optional-username"
    MATTERMOST_ICON_URL: "https://optional-url-here/favicon.ico"
    MATTERMOST_MESSAGE: "My important message goes here on failure! -> ${CI_JOB_URL}"
  rules:
    - on_failure
