---
#########################
# Name: vRA
# Description: An example of the using the vRA jobs to build and teardown the environment.
# Notes:
#   * Set TOWER_TEMPLATE to the name of the template in Tower you want run on the host that gets built.
# Usage:
#   * Copy and paste the below into .gitlab-ci.yml
#   * Modify the TOWER_TEMPLATE for your project.
#   * Include the changes through the MR process.
#########################

stages:
  - vra-build
  - vra-teardown

include:
  - remote: "https://git.saltlabs.cloud/templates/gitlab-ci/-/raw/main/Jobs/vra_build.gitlab-ci.yml"

  - remote: "https://git.saltlabs.cloud/templates/gitlab-ci/-/raw/main/Jobs/vra_teardown.gitlab-ci.yml"

build-environment:
  stage: vra-build
  extends:
    - ".vra-build"
  variables:
    TOWER_TEMPLATE: "gitlab-deploy"

teardown-environment:
  stage: vra-teardown
  extends:
    - ".vra-teardown"
