# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}: self: super: {
  "ClusterShell" = super.buildPythonPackage rec {
    pname = "ClusterShell";
    version = "1.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/48/8c/c8eee7aa92fac6605e3ad81a70c0d00a54787bc32736ce10748c0b8e3467/ClusterShell-1.9.1.tar.gz";
      sha256 = "06zc0wiahl34ydxjs1n37xvjk3ay3qpxb6z17jh8sl0v2k5b62kg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/7e/68018b70268fb4a2a605e2be44ab7b4dd7ce7808adae6c5ef32e34f4b55a/MarkupSafe-2.1.2.tar.gz";
      sha256 = "03a515mrh1l3cynrhcb5rjphmxkwdwd3hin7sii6s0r65f6brjmb";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyJWT" = super.buildPythonPackage rec {
    pname = "PyJWT";
    version = "2.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/40/46/505f0dd53c14096f01922bf93a7abb4e40e29a06f858abbaa791e6954324/PyJWT-2.6.0-py3-none-any.whl";
      sha256 = "052cyrk49w11j9fhkl85aaa61nxamy8glb0s7r6vgfvp5a4ksg6q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyYaml" = super.buildPythonPackage rec {
    pname = "PyYaml";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "acct" = super.buildPythonPackage rec {
    pname = "acct";
    version = "8.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/f5/4d3bbda51f1d9de36715e92d74c16a79dba6dd639742e780cd6fa3d7c78d/acct-8.5.2-py3-none-any.whl";
      sha256 = "1wbjaj0fvl44wbfg1xcgkj4zf6pivpmdak60bfnxi4ipa402jwxh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."aiofiles"
      self."cryptography"
      self."dict-toolbox"
      self."pop"
      self."pop-config"
      self."pop-serial"
      self."rend"
    ];
  };
  "adal" = super.buildPythonPackage rec {
    pname = "adal";
    version = "1.2.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/8d/58008a9a86075827f99aa8bb75d8db515bb9c34654f95e647cda31987db7/adal-1.2.7-py2.py3-none-any.whl";
      sha256 = "0gdwhkqcg7vq1z3j587fg1s79vrh7r520hihf1bvrpa1fknm2x1a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyJWT"
      self."cryptography"
      self."python-dateutil"
      self."requests"
    ];
  };
  "aiofiles" = super.buildPythonPackage rec {
    pname = "aiofiles";
    version = "23.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/76/635aa4f210d46ca105bfedd42d41f649b91d3e58422912726fc5e7965442/aiofiles-23.1.0-py3-none-any.whl";
      sha256 = "1ciywnidn8birz63037nr38sw8va8rg5agqn3mpynwk4w15424lk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "aiohttp" = super.buildPythonPackage rec {
    pname = "aiohttp";
    version = "3.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/fd/1ff4da09ca29d8933fda3f3514980357e25419ce5e0f689041edb8f17dab/aiohttp-3.8.4.tar.gz";
      sha256 = "0p5bj6g7ca19gvwk8fz00k579ma9w9kd27ssh2zl3r61ca8ilbmz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiosignal"
      self."async-timeout"
      self."attrs"
      self."charset-normalizer"
      self."frozenlist"
      self."multidict"
      self."yarl"
    ];
  };
  "aiosignal" = super.buildPythonPackage rec {
    pname = "aiosignal";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl";
      sha256 = "05rvv06k1460w8jcgsv6qsm82zvbnf0frkag9rc6ms6ignq6ydzq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."frozenlist"
    ];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "4.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl";
      sha256 = "0g1v719nh6l516d6f7cq3j2zbz9cwhbf99ficqyl21qdypyf98cc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asyncssh" = super.buildPythonPackage rec {
    pname = "asyncssh";
    version = "2.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/9f/ad61867b12823f6e2c0ef2b80a704273b9385de707ac4539afa445c0665d/asyncssh-2.13.1-py3-none-any.whl";
      sha256 = "0x85z9wjlg2vzr8mz33zcq6jqwixar2dh7zhd9pcr9zrnkiba3n9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."typing-extensions"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "22.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/6e/6f83bf616d2becdf333a1640f1d463fef3150e2e926b7010cb0f81c95e88/attrs-22.2.0-py3-none-any.whl";
      sha256 = "0dh84hdmdqvlyjqw0dqfbvfg6y4gh7w9h3qp96yqv1kqcxzmrs99";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "azure-common" = super.buildPythonPackage rec {
    pname = "azure-common";
    version = "1.1.25";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/4d/d000fc3c5af601d00d55750b71da5c231fcb128f42ac95b208ed1091c2c1/azure_common-1.1.25-py2.py3-none-any.whl";
      sha256 = "02j0v84izsplzdab2j31m3vh5wrfrayrbirb8bad5kf9dljy80px";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "azure-core" = super.buildPythonPackage rec {
    pname = "azure-core";
    version = "1.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/8c/6463dc620629d71c02f3f1a7dc30aab8e4f1a08ef64726cc3dd4f7949096/azure_core-1.8.1-py2.py3-none-any.whl";
      sha256 = "1w5yfp3zbyvakgv01xjn6wmv8j6ymhxz4amdnaag4bm02b0ii7cj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
      self."six"
    ];
  };
  "azure-graphrbac" = super.buildPythonPackage rec {
    pname = "azure-graphrbac";
    version = "0.61.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3e/93/02056aca45162f9fc275d1eaad12a2a07ef92375afb48eabddc4134b8315/azure_graphrbac-0.61.1-py2.py3-none-any.whl";
      sha256 = "0xdiy25v12nysg4svsvhivff9clzilr1rirk5cpr3k3acw2hykkv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-identity" = super.buildPythonPackage rec {
    pname = "azure-identity";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/d8/b2c5fb855983b6e1cfabe1c7105e15562430eabf592d51754ec8924d1f0a/azure_identity-1.4.0-py2.py3-none-any.whl";
      sha256 = "08pjmn7r95f66mzw3gg2vh154llgmp8j4d5pdhc4swn7d9nfmk4j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-core"
      self."cryptography"
      self."msal"
      self."msal-extensions"
      self."six"
    ];
  };
  "azure-keyvault-keys" = super.buildPythonPackage rec {
    pname = "azure-keyvault-keys";
    version = "4.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/d5/a7f1a6963efb2d24af77f250d9bcc63a56bbd9a494d4a345e84014c4f11a/azure_keyvault_keys-4.2.0-py2.py3-none-any.whl";
      sha256 = "18sab1k901slxvw72rnn34acfn81g1qq60yj8gg4p9ip7laxx08z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."azure-core"
      self."cryptography"
      self."msrest"
    ];
  };
  "azure-keyvault-secrets" = super.buildPythonPackage rec {
    pname = "azure-keyvault-secrets";
    version = "4.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/43/ae/4ad0c67e54f820d0ead249ce48e8cf498cfee42034dcd837d8f218ba9e76/azure_keyvault_secrets-4.2.0-py2.py3-none-any.whl";
      sha256 = "18babs6jy4bvdrprzpk4y47s0mz5v6js1x0lfm3r9hwhhm8smf08";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."azure-core"
      self."msrest"
    ];
  };
  "azure-mgmt-applicationinsights" = super.buildPythonPackage rec {
    pname = "azure-mgmt-applicationinsights";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/45/a95820591a0286274c3bb452a592c34fc095edca305a922da22035927ba3/azure_mgmt_applicationinsights-0.2.0-py2.py3-none-any.whl";
      sha256 = "09742hqxqck3qfn0yav1ky967mjzrji0qfqasrrcrcgkh96fk4xy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-authorization" = super.buildPythonPackage rec {
    pname = "azure-mgmt-authorization";
    version = "0.61.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b4/50/7a923f58bf053280fe1890f3332c08f6a82a208c92035ad8f7888c87b786/azure_mgmt_authorization-0.61.0-py2.py3-none-any.whl";
      sha256 = "05sqzlss8cna22gh85jjw30illl1dfxmvqax62cfar80bk6szy1q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-compute" = super.buildPythonPackage rec {
    pname = "azure-mgmt-compute";
    version = "13.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/5d/e42ae8d9f9ee8ba36a800a8eaf16cd14a0ea6cb79d8cccfb203c505cc802/azure_mgmt_compute-13.0.0-py2.py3-none-any.whl";
      sha256 = "1hp7jpv14f8w4mc19lm8x1cw59rd0y4rg5nk0znrpr5nnhvzwj08";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-containerinstance" = super.buildPythonPackage rec {
    pname = "azure-mgmt-containerinstance";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/89/20bf1f4bb8d54f7f6fb96f0743c3b35871a7fac7dd5273c84c7201ff12c4/azure_mgmt_containerinstance-2.0.0-py2.py3-none-any.whl";
      sha256 = "1rrrbl8yf32bv4jsalxdm3w60cfv06mmv1hyjvvy4w6q61y5h20x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-containerregistry" = super.buildPythonPackage rec {
    pname = "azure-mgmt-containerregistry";
    version = "3.0.0rc14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/ba/c61d1194088d88de079ae0d02529229dc15c2f84d43c6b7f6c3ed06fa39d/azure_mgmt_containerregistry-3.0.0rc14-py2.py3-none-any.whl";
      sha256 = "07i6155jzavp5cqa7wm2h32zkjmz1r8012hfrcm0lnn2ny0a5jds";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-dns" = super.buildPythonPackage rec {
    pname = "azure-mgmt-dns";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/e4/135d1b7911321576621d51a70a8f28ef027fe0af9eadff44a0b656586cd1/azure_mgmt_dns-3.0.0-py2.py3-none-any.whl";
      sha256 = "0hgglmzjmxmcr2b3wpr6izxbgv87d12sy3il8nh2777fbcvp7hfa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-keyvault" = super.buildPythonPackage rec {
    pname = "azure-mgmt-keyvault";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/af/1ba15e7176bcf6b1531b453e410ae41a983c09f834d8700dfce739451b53/azure_mgmt_keyvault-2.2.0-py2.py3-none-any.whl";
      sha256 = "1wh79sc8n370wvinknv49xr7vrxhx8kim97c9y5r36rq9ps0ljcb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-loganalytics" = super.buildPythonPackage rec {
    pname = "azure-mgmt-loganalytics";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/0f/23b85bcfaf8ad267a7c552293491c03bac382f9a4e99320d2223ddc62b47/azure_mgmt_loganalytics-0.7.0-py2.py3-none-any.whl";
      sha256 = "1610rsyhm9073wxa93aic9hxzi8qkawcxv0axlk75djh6d45ahp1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-managementgroups" = super.buildPythonPackage rec {
    pname = "azure-mgmt-managementgroups";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/e8/2bbe79c62ad2787944dd7ae4d06d60afb3967b5efc09ed14046919371b59/azure_mgmt_managementgroups-0.2.0-py2.py3-none-any.whl";
      sha256 = "0xd7f5r21xa7ypyy9faqh2dvmbi5lrg3i7gds765x1nzfiifx541";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-monitor" = super.buildPythonPackage rec {
    pname = "azure-mgmt-monitor";
    version = "0.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/5e/a8904655a08522367ba1e4a08db9c3b998875641281d9f31bfb4041a6048/azure_mgmt_monitor-0.11.0-py2.py3-none-any.whl";
      sha256 = "1n2059vpxd8sx7vzpcfcm4dvrpla29ilfn3aab8v1av1qmjxra4i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-msi" = super.buildPythonPackage rec {
    pname = "azure-mgmt-msi";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/34/68/ed34c2646ac06a67df96c31243a50f7af29c14624eff0e8fced137ec6c09/azure_mgmt_msi-1.0.0-py2.py3-none-any.whl";
      sha256 = "1k6vl5jzny4mfnd1nrkdp21m1mh5370ki9fpx30p397r46ppalg7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-network" = super.buildPythonPackage rec {
    pname = "azure-mgmt-network";
    version = "11.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/6f/2f2fa743ec853f20bf151ca139aa4ae3eb3cd6319834a8f780cd634d7716/azure_mgmt_network-11.0.0-py2.py3-none-any.whl";
      sha256 = "0svq2ppmjcw1h3vp909j19qwbq749wvz8a3ravx2qfz385rxljqa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-rdbms" = super.buildPythonPackage rec {
    pname = "azure-mgmt-rdbms";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/91/1085293d9a28f707d3c8a5c6676114be0bb0cfea5e78226d1f7a02df6843/azure_mgmt_rdbms-2.2.0-py2.py3-none-any.whl";
      sha256 = "1scgh8qxqiszr46bqyhscr1mwi6r51jdhn09yv58ddfz574zsnnh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-redis" = super.buildPythonPackage rec {
    pname = "azure-mgmt-redis";
    version = "6.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/7e/e958de2ef701104a35caabe4ad5d1588cd2d413271695924c586549d6a34/azure_mgmt_redis-6.0.0-py2.py3-none-any.whl";
      sha256 = "0511bbk70i7yhsblssnh3aabvzlgbnc66xjbmbymgl4ghs0d0vvm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-resource" = super.buildPythonPackage rec {
    pname = "azure-mgmt-resource";
    version = "8.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/f0/3a3fe6f66a33a4a84e21984b7450475ee031c7d82c09a6d27170f2ccd34e/azure_mgmt_resource-8.0.0-py2.py3-none-any.whl";
      sha256 = "0wy5c995d4iimclm1lrdk2lb332lw4w5nlfpg5w3qrqmmsxi0nj5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-storage" = super.buildPythonPackage rec {
    pname = "azure-mgmt-storage";
    version = "11.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/6c/2f170614e3414e807c8f18a197237a0a54c3cebf770e4cb3b2ef31138f58/azure_mgmt_storage-11.1.0-py2.py3-none-any.whl";
      sha256 = "0phsph8ykik3x023lxl418g6ysxn459a4vc5c32nw0jrqg0si9k2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-mgmt-web" = super.buildPythonPackage rec {
    pname = "azure-mgmt-web";
    version = "0.47.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/76/b6b800d686f38b010d2b911bfb1ef820ff9659e884f2cf2470360546981e/azure_mgmt_web-0.47.0-py2.py3-none-any.whl";
      sha256 = "0bqq6gfl31awyd4aqlfq9b7yx0d501zdg1vlrglmb8a44i1nym6x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-common"
      self."msrest"
      self."msrestazure"
    ];
  };
  "azure-storage-blob" = super.buildPythonPackage rec {
    pname = "azure-storage-blob";
    version = "12.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/3d/31614573e8a197db12d8ab47a7fd813f15bd4a4b5c64e85d23b865de5b9b/azure_storage_blob-12.3.2-py2.py3-none-any.whl";
      sha256 = "01k747qw1g3f73xncwfjr8cyr69fcih8k4nwfhr9c5las8ya60la";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."azure-core"
      self."cryptography"
      self."msrest"
    ];
  };
  "boto3" = super.buildPythonPackage rec {
    pname = "boto3";
    version = "1.24.96";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e2/53/e9c9f18f97f1565d9194c0ebbfb8bd9bd4bbb93a54569d2e7af256980511/boto3-1.24.96-py3-none-any.whl";
      sha256 = "0lsgxa8i6gi4kkpxmqcj1fndycw7i3x4pyf76i678af62i90b33l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."botocore"
      self."jmespath"
      self."s3transfer"
    ];
  };
  "botocore" = super.buildPythonPackage rec {
    pname = "botocore";
    version = "1.27.96";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/73/aa345e22ce21e86fa99e8dc25ab7ae4fd73eedc4c365282c82fa6ba3f66f/botocore-1.27.96-py3-none-any.whl";
      sha256 = "1fggvfzlf35dbb2ldy5yrkngy3jwll1b76ia3ccgkwhihnhq26p4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jmespath"
      self."python-dateutil"
      self."urllib3"
    ];
  };
  "cachetools" = super.buildPythonPackage rec {
    pname = "cachetools";
    version = "5.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/14/2b48a834d349eee94677e8702ea2ef98b7c674b090153ea8d3f6a788584e/cachetools-5.3.0-py3-none-any.whl";
      sha256 = "1m793lns2a17x4vkxvzfcfbnlpdnk15mv8ssr2k8w02whhg1m7j2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2022.12.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl";
      sha256 = "065wqxligjai8la891i71s921q7xmpyc3krixhc6fvcjbqpj7lsa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/a8/050ab4f0c3d4c1b8aaa805f70e26e84d0e27004907c5b8ecc1d31815f92a/cffi-1.15.1.tar.gz";
      sha256 = "1y9lr651svbzf1m03s4lqbnbv2byx8f6f0ml7hjm24vvlfwvy06l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/96/d7/1675d9089a1f4677df5eb29c3f8b064aa1e70c1251a0a8a127803158942d/charset-normalizer-3.0.1.tar.gz";
      sha256 = "0vrjmv6w2hx0paknyq79gxhrrqn60q8r56v9g9fwmy1hz6d37spb";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "colorama" = super.buildPythonPackage rec {
    pname = "colorama";
    version = "0.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl";
      sha256 = "1ijz53xpmxds2qf02l9yf0rnp7bznwh3ci4xkw8wmh5cyn8rj7ag";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "configparser" = super.buildPythonPackage rec {
    pname = "configparser";
    version = "5.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/7a/9d0f52bf4923b2e410c7d6fda472c32d9b728284e89ec99074820226102f/configparser-5.3.0-py3-none-any.whl";
      sha256 = "1ymr95x5317482a4dyx3jqp89fxla51zl0i2wk7g8srwv6gpfrdh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "37.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/d9/5fcd312d5cce0b4d7ee8b551a0ea99e4ea9db0fdbf6dd455a19042e3370b/cryptography-37.0.4.tar.gz";
      sha256 = "10haq7sn8mrdlhcfs791rczknnxm0wpww0lkpjzcqx141ryc3yb3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "5.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl";
      sha256 = "11kisc16y8lmka9khfvnm4gzwaa7x6n5lg4i4lr45p5r01czihxq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "deepdiff" = super.buildPythonPackage rec {
    pname = "deepdiff";
    version = "5.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/98/21e6baf359f03b760331444cda25332e1d1c3911fd57a36e54029489bd91/deepdiff-5.8.1-py3-none-any.whl";
      sha256 = "1dyjw3lqkvfc2jwg340pvfblmngr4s7qs0wp12dankzk6fbs9bp9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ordered-set"
    ];
  };
  "dict-toolbox" = super.buildPythonPackage rec {
    pname = "dict-toolbox";
    version = "3.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/51/fba56ded2d40583f216dcf4579dde8f2f58b797760923943316dbea02bea/dict_toolbox-3.0.2-py3-none-any.whl";
      sha256 = "000ynxfw7d3bmqnlfd6d0apddnp97rn3sy1zdzr8k61r048by6l0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."aiofiles"
      self."msgpack"
    ];
  };
  "frozenlist" = super.buildPythonPackage rec {
    pname = "frozenlist";
    version = "1.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/10/d629476346112b85c912527b9080944fd2c39a816c2225413dbc0bb6fcc0/frozenlist-1.3.3.tar.gz";
      sha256 = "0sispcpras096fxrd0i35qs25fqy4r0x8v1d6f40pag845bwbg2q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "google-api-core" = super.buildPythonPackage rec {
    pname = "google-api-core";
    version = "2.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f7/24/a17e75c733609dce285a2dae6f56837d69a9566963c9d1cab96d788546c8/google_api_core-2.11.0-py3-none-any.whl";
      sha256 = "0vn1kp4rq759mq56jfyc2jmwqvbdk5bbjhxh7v37n3fyn0kjw8nf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."googleapis-common-protos"
      self."protobuf"
      self."requests"
    ];
  };
  "google-api-python-client" = super.buildPythonPackage rec {
    pname = "google-api-python-client";
    version = "2.80.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/63/fea1330ab4966d37a64bfd23378f8c32722ed7b91178cab4ab3601f4fd5e/google_api_python_client-2.80.0-py2.py3-none-any.whl";
      sha256 = "1aq714bkfsa72shn6w2rpvd8444410icbn2h666bgzndq982bkdr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-api-core"
      self."google-auth"
      self."google-auth-httplib2"
      self."httplib2"
      self."uritemplate"
    ];
  };
  "google-auth" = super.buildPythonPackage rec {
    pname = "google-auth";
    version = "2.16.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/c4/16f8ad44ed7544244a9883f35cc99dc96378652a0ec7cc39028b1c697a1e/google_auth-2.16.2-py2.py3-none-any.whl";
      sha256 = "18khczd9y0s58336d8xa51rbagyqnj5ybv5g0kia1lbn93wkrvrg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cachetools"
      self."pyasn1-modules"
      self."rsa"
      self."six"
    ];
  };
  "google-auth-httplib2" = super.buildPythonPackage rec {
    pname = "google-auth-httplib2";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/db/721e2f3f32339080153995d16e46edc3a7657251f167ddcb9327e632783b/google_auth_httplib2-0.1.0-py2.py3-none-any.whl";
      sha256 = "042a3yfgl0ic4mksyqysz4nisghy08zcn5r6x1bknr5mqqv9rr1i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."httplib2"
      self."six"
    ];
  };
  "googleapis-common-protos" = super.buildPythonPackage rec {
    pname = "googleapis-common-protos";
    version = "1.58.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/4e/ed585842aaa704d87495a0e99317aaa44c5007a597c05b995fa8cfc4dfbe/googleapis_common_protos-1.58.0-py2.py3-none-any.whl";
      sha256 = "16jip45c3mxby4lg1293ngs8zdjv2szlcsrm96nvdnl08p6yyfya";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "heist" = super.buildPythonPackage rec {
    pname = "heist";
    version = "6.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/6f/dba2919c8d13b9120581c35e075d93c426b89505f1bfc378c49f3569c5f0/heist-6.2.0-py3-none-any.whl";
      sha256 = "0yfs9pg69kd2d3dzg49x6zjibp1p7vl9g0cgy5q1b1fzdfv9njfj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ClusterShell"
      self."PyYaml"
      self."acct"
      self."aiohttp"
      self."asyncssh"
      self."pop"
      self."rend"
    ];
  };
  "httplib2" = super.buildPythonPackage rec {
    pname = "httplib2";
    version = "0.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/c9/4720a06cc961415e49735e672071b1da1621a347e14a9b1f3728a59a2cbd/httplib2-0.21.0-py3-none-any.whl";
      sha256 = "00fx9k0qh57v3pjj7wfl9ffav8iad45536c6qrhgmlw2xfrqnz4q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
    ];
  };
  "hvac" = super.buildPythonPackage rec {
    pname = "hvac";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/43/6532046afa7b20c352d2a8b68de1d1fd350104024edfb00bf486801712af/hvac-1.0.2-py3-none-any.whl";
      sha256 = "1shzmgmzk91s86xjas467a7jm3vj9jh0k7ylr25v2xi5vr1n69g8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyhcl"
      self."requests"
    ];
  };
  "idem" = super.buildPythonPackage rec {
    pname = "idem";
    version = "20.9.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/57/c33bb208497253c96191934f2af7ac6e3ec07168fea7105af3a6e7fec7fd/idem-20.9.3-py3-none-any.whl";
      sha256 = "0xisriwkdp7wir5g8p4ppajfhvvgbj2ypxwn7h0x86nj65nk63si";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."acct"
      self."aiofiles"
      self."colorama"
      self."dict-toolbox"
      self."jinja2"
      self."jmespath"
      self."pop"
      self."pop-config"
      self."pop-evbus"
      self."pop-loop"
      self."pop-serial"
      self."pop-tree"
      self."rend"
      self."toml"
      self."tqdm"
      self."uvloop"
      self."wheel"
    ];
  };
  "idem-aiohttp" = super.buildPythonPackage rec {
    pname = "idem-aiohttp";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/38/4791b8b0f084cf6a93188b24d7aa9145351cb5e987997f1e7b4930c1f18d/idem_aiohttp-3.0.0-py3-none-any.whl";
      sha256 = "1bqzmp3s6wpnqhpn0d8jqy48q920vgbm52rjvfix3fi4fm33xyl0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohttp"
      self."idem"
      self."pop"
      self."pop-config"
      self."pop-loop"
      self."rend"
    ];
  };
  "idem-aws" = super.buildPythonPackage rec {
    pname = "idem-aws";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/3f/b0ad933133ffc82fdc7da2f9ea72abfeb3b5c5726906e4ec17885ff6a3cf/idem_aws-1.6.0-py3-none-any.whl";
      sha256 = "0x0l47y74nfnywaar8sbw8nrh5vadykk4lhgcm9jcsz5qwxk3779";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."acct"
      self."boto3"
      self."configparser"
      self."cryptography"
      self."deepdiff"
      self."heist"
      self."idem"
      self."pgpy"
      self."pop-serial"
      self."pycryptodomex"
    ];
  };
  "idem-azure" = super.buildPythonPackage rec {
    pname = "idem-azure";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/5a/e3e2c9d0fe200376873f5e938e63043b5ea10f1f22f34c685aaf1acc7d15/idem_azure-0.3.0-py3-none-any.whl";
      sha256 = "0ynm9rzigb34135czhm848cka8hz8h5xgzrqq7kjlyxszyibq8kv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."dict-toolbox"
      self."idem"
      self."idem-aiohttp"
      self."validators"
    ];
  };
  "idem-azurerm" = super.buildPythonPackage rec {
    pname = "idem-azurerm";
    version = "4.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/17/b7/da2d8b8b9481bed222438198fdf6c900905e70142b407533c637995643ed/idem_azurerm-4.0.0-py3-none-any.whl";
      sha256 = "0d84rz2cwl8k6k82zdml86lgivkxx6g68hsg5njmbm1nqc0y8wqn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."acct"
      self."azure-common"
      self."azure-core"
      self."azure-graphrbac"
      self."azure-identity"
      self."azure-keyvault-keys"
      self."azure-keyvault-secrets"
      self."azure-mgmt-applicationinsights"
      self."azure-mgmt-authorization"
      self."azure-mgmt-compute"
      self."azure-mgmt-containerinstance"
      self."azure-mgmt-containerregistry"
      self."azure-mgmt-dns"
      self."azure-mgmt-keyvault"
      self."azure-mgmt-loganalytics"
      self."azure-mgmt-managementgroups"
      self."azure-mgmt-monitor"
      self."azure-mgmt-msi"
      self."azure-mgmt-network"
      self."azure-mgmt-rdbms"
      self."azure-mgmt-redis"
      self."azure-mgmt-resource"
      self."azure-mgmt-storage"
      self."azure-mgmt-web"
      self."azure-storage-blob"
      self."dict-toolbox"
      self."idem"
      self."msrest"
      self."msrestazure"
      self."pop"
      self."pop-config"
      self."takara"
      self."websocket-client"
    ];
  };
  "idem-gcp" = super.buildPythonPackage rec {
    pname = "idem-gcp";
    version = "0.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/d3/61f12e92343b2e152cf746e5d036e2ba83186ebd02a71017005b9049149c/idem_gcp-0.13.0-py3-none-any.whl";
      sha256 = "1lwjfpjx2sdjzavhi1d1b91bp9k47lz9fsahiq7hx00indp3spzm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohttp"
      self."deepdiff"
      self."google-api-python-client"
      self."idem"
      self."idem-aiohttp"
      self."importlib-resources"
      self."pop"
    ];
  };
  "idem-gitlab" = super.buildPythonPackage rec {
    pname = "idem-gitlab";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/bb/22620efa1f4c34e576de7d4a80cff22f75d867676685a8ca75345d7beb68/idem_gitlab-1.0.0-py3-none-any.whl";
      sha256 = "1ckbvn28aih38vhr8pzmlnz331czs7393ci49gd2vmlaacmdamn9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idem-aiohttp"
      self."pop"
    ];
  };
  "idem-helm" = super.buildPythonPackage rec {
    pname = "idem-helm";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/7f/5ef7dbec188e6c4a85fcb5d568a2f6c718d8b0c3ab00c455c3d32adb69ed/idem_helm-0.1.0-py3-none-any.whl";
      sha256 = "19v9hrvw3glsx8zhjdxikkq5arkgy43y0h0270b7pki2q8s55bm6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deepdiff"
      self."idem"
      self."idem-posix"
      self."pop"
      self."pop-config"
    ];
  };
  "idem-k8s" = super.buildPythonPackage rec {
    pname = "idem-k8s";
    version = "0.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/a2/dccb6712908fc55b47a2dc45d8f01d29f2d27e87c565f19ab114926926b8/idem_k8s-0.4.1-py3-none-any.whl";
      sha256 = "1w61ric1m85y7jhda7mx7832lkfn3dk4iskldn4j59vcfxdakhsx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deepdiff"
      self."idem"
      self."jmespath"
      self."kubernetes"
      self."pop"
      self."pop-config"
    ];
  };
  "idem-posix" = super.buildPythonPackage rec {
    pname = "idem-posix";
    version = "3.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/6d/d66e932eb76da7bdc1f08a58fc92c3c20663942c2476ff075e666d1e8747/idem_posix-3.3.0-py3-none-any.whl";
      sha256 = "1c43w9yykhlxh7nznrhd186bakhz2v0fxl7f1jhyjhw8n6kk11l6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idem"
      self."pop"
    ];
  };
  "idem-salt" = super.buildPythonPackage rec {
    pname = "idem-salt";
    version = "2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/85/747a538511cb22b439ddc6f65c703068812a4d7876729f30947d1a91ba62/idem-salt-2.2.tar.gz";
      sha256 = "1bw7chqvsn20r1sxp7l3j2hff9sxb80gzczwvl71r697fhalacg6";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idem-vault" = super.buildPythonPackage rec {
    pname = "idem-vault";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/2d/c31887603556fc15e9cbcbf9b70ef53b6c52521e21a7e5da59872b007cad/idem_vault-0.3.0-py3-none-any.whl";
      sha256 = "0nj5iknxyjb1r17wpblqj033n86vxx7y6pslc8c3abccqk7ypbk3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."hvac"
      self."idem"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl";
      sha256 = "1hn54ps4kgv2fmyvfaks38sgrvjc1cn4834sh7gadsx3x9wpxdwh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-resources" = super.buildPythonPackage rec {
    pname = "importlib-resources";
    version = "5.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/71/c13ea695a4393639830bf96baea956538ba7a9d06fcce7cef10bfff20f72/importlib_resources-5.12.0-py3-none-any.whl";
      sha256 = "06m8c6hcqhwx2d4x7q4nqbz5z2yfl8zzdwlvw1w7a71mpzmyw7bv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "isodate" = super.buildPythonPackage rec {
    pname = "isodate";
    version = "0.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/85/7882d311924cbcfc70b1890780763e36ff0b140c7e51c110fc59a532f087/isodate-0.6.1-py2.py3-none-any.whl";
      sha256 = "15pdrf3iq71qfg7hfgvr70mpj5fqkra4ypyk9686aqj1jk7fwl87";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl";
      sha256 = "0q9a30x046p3wvbgx598g4lmxwwykk0vjsjl21khx7r3zq5r7230";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "jmespath" = super.buildPythonPackage rec {
    pname = "jmespath";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl";
      sha256 = "10194nk0641vz2kpy442dsgdv44ia43zksrf6f4apg5mf76f9qh2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kubernetes" = super.buildPythonPackage rec {
    pname = "kubernetes";
    version = "23.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/08/fbf2860d564958a36f12c99e299fc3103ff72ccbd3fe11343a4ea044fb0a/kubernetes-23.3.0-py2.py3-none-any.whl";
      sha256 = "0nwglfxcdcf10j2ycfp81ff1wplc62i0jpslcpxj1g75xkqghgr2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."certifi"
      self."google-auth"
      self."python-dateutil"
      self."requests"
      self."requests-oauthlib"
      self."setuptools"
      self."six"
      self."urllib3"
      self."websocket-client"
    ];
  };
  "lazy-object-proxy" = super.buildPythonPackage rec {
    pname = "lazy-object-proxy";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/c0/8bab72a73607d186edad50d0168ca85bd2743cfc55560c9d721a94654b20/lazy-object-proxy-1.9.0.tar.gz";
      sha256 = "1bpbqhd0s09y7fjxv2dkzckfyyzwkik6y4653a59nqm4ky0bb7v5";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "msal" = super.buildPythonPackage rec {
    pname = "msal";
    version = "1.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/86/9900755d4be6e36b48603f9056ffca341d42139297df6f7e143fa96e6ed7/msal-1.21.0-py2.py3-none-any.whl";
      sha256 = "0shc5fyvbvy9767mzh52lk7aq0k00fa4yp9znxxzzkgcq4blci78";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyJWT"
      self."cryptography"
      self."requests"
    ];
  };
  "msal-extensions" = super.buildPythonPackage rec {
    pname = "msal-extensions";
    version = "0.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/33/da/eed514cb6902405c5c11a03f1e65adbd95e2c26d9b22eae390eddb561201/msal_extensions-0.2.2-py2.py3-none-any.whl";
      sha256 = "0cp5in5z5yriwn063dbribz30y43zgnpp7rwdinwjphlhxkj94ph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."msal"
      self."portalocker"
    ];
  };
  "msgpack" = super.buildPythonPackage rec {
    pname = "msgpack";
    version = "1.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/44/0829b19ac243211d1d2bd759999aa92196c546518b0be91de9cacc98122a/msgpack-1.0.4.tar.gz";
      sha256 = "0pqzy1zclyhd42gfibhkcqymbspy5a6v421g87mh40h3iz0nkn7m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "msrest" = super.buildPythonPackage rec {
    pname = "msrest";
    version = "0.6.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/f5/9e315fe8cb985b0ce052b34bcb767883dc739f46fadb62f05a7e6d6eedbe/msrest-0.6.19-py2.py3-none-any.whl";
      sha256 = "0abr5445hk9wbfv946v2whadfs1y95024vcmyvvdpwryija69al7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."isodate"
      self."requests"
      self."requests-oauthlib"
    ];
  };
  "msrestazure" = super.buildPythonPackage rec {
    pname = "msrestazure";
    version = "0.6.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/3a/7adb08fd2f0ee6fdfd03685fac38477b64f184943dcf6ea0cbffb205f22d/msrestazure-0.6.4-py2.py3-none-any.whl";
      sha256 = "1fg53lggw37sn1659w1kxzn6h139jqj9i6h93srjkxby2ib0zr9x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."adal"
      self."msrest"
      self."six"
    ];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/15/bd620f7a6eb9aa5112c4ef93e7031bcd071e0611763d8e17706ef8ba65e0/multidict-6.0.4.tar.gz";
      sha256 = "0jfsq7dnaja8jnd4ih02fhp6ic2ryhn7zfg7q19n9dzgj9j90rin";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nest-asyncio" = super.buildPythonPackage rec {
    pname = "nest-asyncio";
    version = "1.5.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/1a/6dd9ec31cfdb34cef8fea0055b593ee779a6f63c8e8038ad90d71b7f53c0/nest_asyncio-1.5.6-py3-none-any.whl";
      sha256 = "1f780vxwyim1ahj6ah34n6103411vfc90q09s63sbsnw83xm7adr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "oauthlib" = super.buildPythonPackage rec {
    pname = "oauthlib";
    version = "3.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/80/cab10959dc1faead58dc8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl";
      sha256 = "1jpvcxq0xr3z50fdg828in1icgz8cfcy3sc04r85vqhkmjdg4fc1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ordered-set" = super.buildPythonPackage rec {
    pname = "ordered-set";
    version = "4.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/33/55/af02708f230eb77084a299d7b08175cff006dea4f2721074b92cdb0296c0/ordered_set-4.1.0-py3-none-any.whl";
      sha256 = "0qj5w4fn3pi37s1rc92qpkfm3brcjcl9jlwa8cq37kqzqwr12vh4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pgpy" = super.buildPythonPackage rec {
    pname = "pgpy";
    version = "0.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/3a/b687f374726e8f120aa434314365e89d75f24060e49b4d301f238f3820d6/PGPy-0.5.4-py2.py3-none-any.whl";
      sha256 = "1a96dyc9affsnjczv1717mm2nmd7fx78j41lfz1pardspjrdk6n2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."pyasn1"
      self."six"
    ];
  };
  "pop" = super.buildPythonPackage rec {
    pname = "pop";
    version = "23.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/66/54/55bccb9df558ba4567c2c39b53ed6f6adee2d1267a06d1e640d4d0305b3a/pop-23.0.0-py3-none-any.whl";
      sha256 = "1hzg0x7f9vmnghcnkgxr63y6x9z11wfqcwrivqrwnc3anbba4wgl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."dict-toolbox"
      self."lazy-object-proxy"
      self."pop-config"
      self."pop-loop"
    ];
  };
  "pop-config" = super.buildPythonPackage rec {
    pname = "pop-config";
    version = "12.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/d0/acf2b061c137f609f8bda95abbed5aa53d1c6db6967b5e6308a58ae61718/pop_config-12.0.1-py3-none-any.whl";
      sha256 = "1289vrrrfnwqhw5m8f7l0mgdkfhab0rdnib25xv4if74i9g0ld7q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."dict-toolbox"
      self."pop"
      self."rend"
    ];
  };
  "pop-evbus" = super.buildPythonPackage rec {
    pname = "pop-evbus";
    version = "6.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/4f/131fc00ed844eb9afe81ae919ccf38b43521f9d994220ec7a686c19d97ac/pop_evbus-6.2.2-py3-none-any.whl";
      sha256 = "1m160a2wd3iajaa27gn70v126ik9grczrzkx61ihfv2i5xg32s9p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."acct"
      self."msgpack"
      self."pop"
      self."pop-serial"
      self."rend"
    ];
  };
  "pop-loop" = super.buildPythonPackage rec {
    pname = "pop-loop";
    version = "1.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/7e/4a4b235506486dfef094c71f94b0825a75359777839dd539432e86d26501/pop_loop-1.0.6-py3-none-any.whl";
      sha256 = "1861c4qsz6kjbnn3c9r80ahfx3a1ckbw2nyrj7cvk06plyyk15if";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."nest-asyncio"
      self."pop"
      self."sniffio"
    ];
  };
  "pop-serial" = super.buildPythonPackage rec {
    pname = "pop-serial";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/13/83ba049f209b7b9d98ef532af4c4c72ce050b2f3c31ebb16cff7dac7e1db/pop_serial-1.1.1-py3-none-any.whl";
      sha256 = "1b9r96fvmf7qh0ypq2vys1glsw6mzs4zvpbw7i685bl3a5f08z6s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."msgpack"
      self."pop"
    ];
  };
  "pop-tree" = super.buildPythonPackage rec {
    pname = "pop-tree";
    version = "9.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/23/0e1023d1cfe387c5a4d8408a90bc8377f39bb5a75b2d4188baf3f2bcd39c/pop_tree-9.3.1-py3-none-any.whl";
      sha256 = "12xbn2g3jihl6da3sj5cm0qk96jyppa0laiwbh4zj6kpq1yc5mkw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiofiles"
      self."pop"
      self."rend"
    ];
  };
  "portalocker" = super.buildPythonPackage rec {
    pname = "portalocker";
    version = "1.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/e7/ceef002a300a98a208232fab593183249b6964b306ee7dabb29908419cca/portalocker-1.7.1-py2.py3-none-any.whl";
      sha256 = "0jlxkz1szpjv0mcsqkmcj8ykx2l4q76nvcxyg68cv2yq3333djrl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "4.22.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/95/797a257a5db4a91dc2bc864c487ead56440014d741933a28c86d966b949e/protobuf-4.22.0.tar.gz";
      sha256 = "0c2rmj25j09f338rj6d4xw0d6mg4647g7zpbivcj8ahjrvz8sbb5";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1" = super.buildPythonPackage rec {
    pname = "pyasn1";
    version = "0.4.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl";
      sha256 = "0pda8szs8jsaknf4ggilgn2q8vpwdm2nzyw79vzlfnai63nf5irr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1-modules" = super.buildPythonPackage rec {
    pname = "pyasn1-modules";
    version = "0.2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl";
      sha256 = "0x0cilayca3lm2wahmxz3z9v7jqnn3v82nfj3mhb6z5rzs7q02x5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.21";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl";
      sha256 = "1agwca0hgbpwmr9snhxafqjhfd52mq083rw5n7vf25amallm9r4f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycryptodomex" = super.buildPythonPackage rec {
    pname = "pycryptodomex";
    version = "3.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/21/f399ba8dfd6e40eee444151af3237af22788b8b16077c75ec0419125f619/pycryptodomex-3.13.0.tar.gz";
      sha256 = "1sgk9yh4ivlbg4hy6471k8x7krmjbjp8q0nlql1xsdvq4hq34i33";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyhcl" = super.buildPythonPackage rec {
    pname = "pyhcl";
    version = "0.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/b0/dd4f1d01b77be3b66d9f550ed958b68fa553764be1d27c7d604906c06b42/pyhcl-0.4.4.tar.gz";
      sha256 = "00xhh7h4r91ha5cqsm9fynrwa14ir5rblqfmzqmq2g82y76rv6rd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
    ];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.0.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl";
      sha256 = "1g3b426kswh9ndjdlkpf9ba0fhwz5c2hjbxb3nvfzshfl7lvl9jh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl";
      sha256 = "1aaxjfp4lrz8c6qls3vdhw554lan3khy9afyvdcvrssk6kf067cn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "rend" = super.buildPythonPackage rec {
    pname = "rend";
    version = "6.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/9b/32e1a5d7056db1ef06279ada958c2aa031b8f77badbf947cee175a67d683/rend-6.5.2-py3-none-any.whl";
      sha256 = "0210xwdlm2vyz54n4f0s9imzkv2fq2agqdqla1s9l1f66phzgx58";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."colorama"
      self."dict-toolbox"
      self."jinja2"
      self."pop"
      self."toml"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/f4/274d1dbe96b41cf4e0efb70cbced278ffd61b5c7bb70338b62af94ccb25b/requests-2.28.2-py3-none-any.whl";
      sha256 = "1alba73bi3rnpns28wf3b7ii2y0d3iw0n0rcc93sfg92154ryab4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "requests-oauthlib" = super.buildPythonPackage rec {
    pname = "requests-oauthlib";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/bb/5deac77a9af870143c684ab46a7934038a53eb4aa975bc0687ed6ca2c610/requests_oauthlib-1.3.1-py2.py3-none-any.whl";
      sha256 = "1dfspmj87kr7nc1d22aqy7z0dhs7dq6hk7f00jihb3gvl80waxr5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."oauthlib"
      self."requests"
    ];
  };
  "rsa" = super.buildPythonPackage rec {
    pname = "rsa";
    version = "4.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/97/fa78e3d2f65c02c8e1268b9aba606569fe97f6c8f7c2d74394553347c145/rsa-4.9-py3-none-any.whl";
      sha256 = "1xvlc59ipksbkz746bkxibnpwwm8bzvhwk9lcxlph575b280s9lh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "s3transfer" = super.buildPythonPackage rec {
    pname = "s3transfer";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/c6/af903b5fab3f9b5b1e883f49a770066314c6dcceb589cf938d48c89556c1/s3transfer-0.6.0-py3-none-any.whl";
      sha256 = "1kayip95pym87m33l4s7fq5h8aa4kb11ynpjnkqn2px1yds6n5q6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."botocore"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sniffio" = super.buildPythonPackage rec {
    pname = "sniffio";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl";
      sha256 = "112k8azxisfcwpvx36rpgisxf15lxv0zgaza5snvggsv3v7gvkpf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "takara" = super.buildPythonPackage rec {
    pname = "takara";
    version = "1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/53/1e/0dcbfea5e713c9c4731d51afb14e12627586009bd02baf4cdab1e6c1c5dc/takara-1.2-py3-none-any.whl";
      sha256 = "1a661bzlzp6sq45d922b85vklsaqnsbgilqk2aapab84bsrm84b6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYaml"
      self."cryptography"
      self."msgpack"
      self."pop"
    ];
  };
  "toml" = super.buildPythonPackage rec {
    pname = "toml";
    version = "0.10.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl";
      sha256 = "16sgpg57kxx5jh467d9qwc2hwshfvdbl0xkafdp3qspvbfp46qc0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tqdm" = super.buildPythonPackage rec {
    pname = "tqdm";
    version = "4.65.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/02/a2cff6306177ae6bc73bc0665065de51dfb3b9db7373e122e2735faf0d97/tqdm-4.65.0-py3-none-any.whl";
      sha256 = "0wcnkv4ysw5a61p2w71qp7hzzs0vccic1vmwba0k5q9pzqbkmxf4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/25/5abcd82372d3d4a3932e1fa8c3dbf9efac10cc7c0d16e78467460571b404/typing_extensions-4.5.0-py3-none-any.whl";
      sha256 = "1d0ijp0h547p1zg34jpx03fyxcx8jg1fnc8ldp0qm6fx75f0hczv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "uritemplate" = super.buildPythonPackage rec {
    pname = "uritemplate";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c0/7461b49cd25aeece13766f02ee576d1db528f1c37ce69aee300e075b485b/uritemplate-4.1.1-py2.py3-none-any.whl";
      sha256 = "0bp08jq51nrjha3sgfc4dwk3d2cflfa5kl7alhp33pcvv6w0h343";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ca/466766e20b767ddb9b951202542310cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl";
      sha256 = "1qd7xh7ply92kyanm6nb5shymk9k77yckhx64iqi6nyqyz1cvvbm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "uvloop" = super.buildPythonPackage rec {
    pname = "uvloop";
    version = "0.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/86/6dda1760481abf244cbd3908b79a4520d757040ca9ec37a79fc0fd01e2a0/uvloop-0.17.0.tar.gz";
      sha256 = "1qdrj6fqm7mrzd2mnznybgmpikxj2ngz71qlqwi1l6pikjpnppqd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "validators" = super.buildPythonPackage rec {
    pname = "validators";
    version = "0.20.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/14/ed0af6865d378cfc3c504aed0d278a890cbefb2f1934bf2dbe92ecf9d6b1/validators-0.20.0.tar.gz";
      sha256 = "0si2pj974vpbwym0zls7dcqmbsxgwwikw8v7wbas4021wvj8q514";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
    ];
  };
  "websocket-client" = super.buildPythonPackage rec {
    pname = "websocket-client";
    version = "0.56.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl";
      sha256 = "1a8aqn714qdfvxjm22ilsmfvqjsyclki4bi9cj8i5p327bxxal8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "yarl" = super.buildPythonPackage rec {
    pname = "yarl";
    version = "1.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/1e/1b204050c601d5cd82b45d5c8f439cb6f744a2ce0c0a6f83be0ddf0dc7b2/yarl-1.8.2.tar.gz";
      sha256 = "0qhm1dwwd8wp3fwh88qrip23b19jymmvy0l6jz83l0g3qq139m29";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."multidict"
    ];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/fa/c9e82bbe1af6266adf08afb563905eb87cab83fde00a0a08963510621047/zipp-3.15.0-py3-none-any.whl";
      sha256 = "0mnmg9nwhrbnb55i7d1ssi7c79f14rbxkphs2npl5rb0db3lz428";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
