---
name: Cleanup

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  # TODO: REMOVE THIS
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  matrix:
    name: Matrix

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v3

      - id: generate_matrix
        name: Generating a matrix of container names
        run: |
          echo "Generating matrix of container names..."
          CONTAINER_NAMES=$(find oci -mindepth 1 -type d ! -name "_template" ! -name "_disabled*" -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
          echo "${CONTAINER_NAMES}" | jq .
          echo "CONTAINER_MATRIX=${CONTAINER_NAMES}" >> "$GITHUB_OUTPUT"

    outputs:
      container_matrix: ${{ steps.generate_matrix.outputs.CONTAINER_MATRIX }}

  cleanup:
    name: Cleanup Packages

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    needs: matrix

    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJson(needs.matrix.outputs.container_matrix) }}
        os:
          - ubuntu-latest

    steps:
      - name: Clean GHCR packages
        uses: cresh-io/action-ghcr-batch-delete-versions@v1
        with:
          github-access-token: "${{ secrets.PAT_PACKAGES }}"
          org: "${{ github.repository_owner }}"
          package_name: "${{ github.repository }}/${{ matrix.container }}"
          package_type: "container"
          dry-run: "0"
          selector: |
            type=tagCount;operator=greaterThan;value=0
          #excluder: |
          #  type=tags;operator=equals;value=2023
        continue-on-error: true

      - uses: duskmoon314/action-delete-ghcr-untagged@v1
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          owner_type: org
          owner: ${{ github.repository_owner }}
          package_name: ${{ github.repository }}/${{ matrix.container }}
          expiration: 0
        continue-on-error: true

      - uses: duskmoon314/action-delete-ghcr-untagged@v1
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          owner_type: org
          owner: ${{ github.repository_owner }}
          package_name: devsecops/${{ matrix.container }}
          expiration: 0
        continue-on-error: true

      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          organization: salt-labs
          container: ${{ github.repository }}/${{ matrix.container }}
          dry-run: false
          keep-younger-than: 0
          keep-last: 0
          prune-untagged: true
        continue-on-error: true

      - name: Prune devsecops
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          organization: salt-labs
          container: devsecops/${{ matrix.container }}
          dry-run: false
          keep-younger-than: 0
          keep-last: 0
          prune-untagged: true
        continue-on-error: true
