---
name: Cleanup

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  # TODO: REMOVE THIS
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  matrix:
    name: Matrix

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v3

      - id: generate_matrix
        name: Generating a matrix of container names
        run: |
          echo "Generating matrix of container names..."
          CONTAINER_NAMES=$(find oci -mindepth 1 -type d ! -name "_template" ! -name "_disabled*" -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
          echo "${CONTAINER_NAMES}" | jq .
          echo "CONTAINER_MATRIX=${CONTAINER_NAMES}" >> "$GITHUB_OUTPUT"

    outputs:
      container_matrix: ${{ steps.generate_matrix.outputs.CONTAINER_MATRIX }}

  cleanup:
    name: Cleanup Packages

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    needs: matrix

    strategy:
      fail-fast: true
      matrix:
        container: ${{ fromJson(needs.matrix.outputs.container_matrix) }}
        os:
          - ubuntu-latest

    steps:
      - id: cleanup_packages
        name: Cleanup ${{ matrix.container }} packages
        uses: actions/delete-package-versions@v4
        with:
          owner: salt-labs/devsecops
          package-name: ${{ matrix.container }}
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
