---
name: Cleanup

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  # TODO: REMOVE THIS
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  matrix:
    name: Matrix

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v3

      - id: generate_matrix
        name: Generating a matrix of container names
        run: |
          echo "Generating matrix of container names..."
          CONTAINER_NAMES=$(find oci -mindepth 1 -type d ! -name "_template" ! -name "_disabled*" -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
          echo "${CONTAINER_NAMES}" | jq .
          echo "CONTAINER_MATRIX=${CONTAINER_NAMES}" >> "$GITHUB_OUTPUT"

    outputs:
      container_matrix: ${{ steps.generate_matrix.outputs.CONTAINER_MATRIX }}

  cleanup:
    name: Cleanup Packages

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    needs: matrix

    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJson(needs.matrix.outputs.container_matrix) }}
        os:
          - ubuntu-latest

    steps:
      - id: cleanup_weekly
        name: Delete all untagged containers older than one week
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ matrix.container }}
          cut-off: A week ago UTC
          account-type: org
          org-name: salt-labs
          #keep-at-least: 1
          keep-at-least: 0
          untagged-only: true
          token: ${{ secrets.PAT_PACKAGES }}

      - name: Delete all containers older than one month
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ matrix.container }}
          cut-off: one min ago UTC+10
          #cut-off: One month ago UTC
          account-type: org
          org-name: salt-labs
          keep-at-least: 0
          #skip-tags: latest
          untagged-only: false
          token: ${{ secrets.PAT_PACKAGES }}

      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: salt-labs/devsecops
          name: ${{ matrix.container }}
          token: ${{ secrets.PAT_PACKAGES }}
          untagged-keep-latest: 0

      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: salt-labs
          name: ${{ matrix.container }}
          token: ${{ secrets.PAT_PACKAGES }}
          untagged-keep-latest: 0

      - name: Delete all owner containers without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          owner_type: org
          repository_owner: ${{ github.repository_owner }}
          untagged_only: false

      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          repository_owner: ${{ github.repository_owner }}
          repository: devsecops
          untagged_only: false
          owner_type: org

      - name: Delete all containers from package
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: ${{ matrix.container }}
          untagged_only: false
          owner_type: org

      - uses: d22/cleanup-ghcr-containers-action@v0.3.3
        with:
          access-token: ${{ secrets.PAT_PACKAGES }}
          package-name: ${{ matrix.container }}
          versions-to-keep: 0
