---
name: Nix Flake check

on:
  push:
    branches:
      - trunk
    paths:
      - .github/workflows/nix-flake-check.yml
      - flake.nix
      - flake.lock
      - containers/*
      - devshells/*
      - scripts/*

  pull_request:
    branches:
      - "trunk"
    paths:
      - .github/workflows/nix-flake-check.yml
      - flake.nix
      - flake.lock
      - containers/*
      - devshells/*
      - scripts/*

permissions:
  contents: read

env:
  NIXPKGS_ALLOW_UNFREE: 1
  RUST_BACKTRACE: 1

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v20

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: salt-labs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Nix Flake check
        run: >-
          nix flake check
          --no-build
          --refresh
          --keep-going
          --verbose
          --impure

      - name: Statix check
        run: nix run nixpkgs#statix -- check
