---
name: Nix Flake check

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - "trunk"
    paths:
      - .github/workflows/**
      - devenv.nix
      - flake.lock
      - flake.nix
      - nix/**
      - scripts/*

permissions:
  contents: read

env:
  NIXPKGS_ALLOW_UNFREE: 1
  RUST_BACKTRACE: 1

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v23

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v13
        with:
          name: salt-labs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Nix Flake check
        run: >-
          nix flake check
          --no-build
          --refresh
          --keep-going
          --verbose
          --impure

      - name: Statix check
        run: nix run nixpkgs#statix -- check
