---
name: Update

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: read

env:
  NIXPKGS_ALLOW_UNFREE: 1

  PROJECT: ${{ github.repository }}

  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

defaults:
  run:
    shell: bash

jobs:
  ##################################################
  # Update
  ##################################################

  update:
    name: Update

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          enable_kvm: true

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v14
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: cache
        name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - id: devenv_install
        name: Devenv install
        run: |
          nix profile install tarball+https://install.devenv.sh/latest

      - id: devenv_gc
        name: Devenv gc
        run: |
          devenv gc

      - id: devenv_update
        name: Devenv update
        run: |
          devenv update

      - id: create_pull_request
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update devenv.lock"
          title: "Update devenv.lock"
          body: "This PR updates the devenv input dependencies"
          branch: "update-devenv-lock"
          base: ${{ env.BRANCH_NAME_DEFAULT }}
          labels: "dependencies"
          assignees: "MAHDTech"
          reviewers: "MAHDTech"
          draft: false
          signoff: true
          delete-branch: true
